"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

format = """
[\u256d\u2500\ue0b6](error)\
$shell\
[\ue0b0](bg:secondary fg:error)\
$directory\
[\ue0b0](bg:secondary_container fg:secondary)\
$git_branch\
$git_status\
[\ue0b0](fg:secondary_container bg:tertiary)\
$time\
[\ue0b0](fg:tertiary)\
\n\
[\u2570\u2500\ue285\ueab6](fg:primary)
"""

palette = 'dark'

[shell]
unknown_indicator = 'mystery shell'
style = 'bg:error fg:on_error'
format = '[ $indicator ]($style)'
disabled = false


[os]
disabled = false
style = "bg:primary fg:on_primary"

[os.symbols]
Arch = "󰣇"

[directory]
style = "bg:secondary fg:on_primary"
format = "[ \uf07b\uea9c $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:tertiary"
format = '[[ $symbol $branch ](fg:on_secondary_container bg:secondary_container)]($style)'

[git_status]
style = "bg:tertiary"
format = '[[($all_status$ahead_behind )](fg:on_secondary_container bg:secondary_container)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:tertiary"
format = '[[  $time ](fg:on_secondary bg:tertiary)]($style)'

[palettes.dark]

background = "#0c1516"

error = "#ffb4ab"

error_container = "#93000a"

inverse_on_surface = "#293234"

inverse_primary = "#825500"

inverse_surface = "#dbe4e6"

on_background = "#dbe4e6"

on_error = "#690005"

on_error_container = "#ffdad6"

on_primary = "#452b00"

on_primary_container = "#ffddb3"

on_primary_fixed = "#291800"

on_primary_fixed_variant = "#633f00"

on_secondary = "#2c2d4d"

on_secondary_container = "#e1e0ff"

on_secondary_fixed = "#171837"

on_secondary_fixed_variant = "#434465"

on_surface = "#dbe4e6"

on_surface_variant = "#b8cacd"

on_tertiary = "#00363d"

on_tertiary_container = "#a9eef9"

on_tertiary_fixed = "#001f24"

on_tertiary_fixed_variant = "#004f57"

outline = "#839497"

outline_variant = "#39494c"

primary = "#f9bb64"

primary_container = "#633f00"

primary_fixed = "#ffddb3"

primary_fixed_dim = "#f9bb64"

scrim = "#000000"

secondary = "#c3c3eb"

secondary_container = "#434465"

secondary_fixed = "#e1e0ff"

secondary_fixed_dim = "#c3c3eb"

shadow = "#000000"

source_color = "#518280"

surface = "#0c1516"

surface_bright = "#323b3c"

surface_container = "#182123"

surface_container_high = "#222c2d"

surface_container_highest = "#2d3638"

surface_container_low = "#141d1f"

surface_container_lowest = "#071011"

surface_dim = "#0c1516"

surface_tint = "#f9bb64"

surface_variant = "#39494c"

tertiary = "#8dd1dd"

tertiary_container = "#004f57"

tertiary_fixed = "#a9eef9"

tertiary_fixed_dim = "#8dd1dd"

