$image = Pictures/Wallpapers/paper-planes-and-dreams.jpg

$background = rgba(0c1516ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(293234ff)

$inverse_primary = rgba(815600ff)

$inverse_surface = rgba(dbe4e6ff)

$on_background = rgba(dbe4e6ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(442b00ff)

$on_primary_container = rgba(ffddb1ff)

$on_primary_fixed = rgba(291800ff)

$on_primary_fixed_variant = rgba(624000ff)

$on_secondary = rgba(2d2d4dff)

$on_secondary_container = rgba(e2dfffff)

$on_secondary_fixed = rgba(181837ff)

$on_secondary_fixed_variant = rgba(444465ff)

$on_surface = rgba(dbe4e6ff)

$on_surface_variant = rgba(b8cacdff)

$on_tertiary = rgba(00363dff)

$on_tertiary_container = rgba(a9eefaff)

$on_tertiary_fixed = rgba(001f24ff)

$on_tertiary_fixed_variant = rgba(004f58ff)

$outline = rgba(839497ff)

$outline_variant = rgba(39494dff)

$primary = rgba(f7bc63ff)

$primary_container = rgba(624000ff)

$primary_fixed = rgba(ffddb1ff)

$primary_fixed_dim = rgba(f7bc63ff)

$scrim = rgba(000000ff)

$secondary = rgba(c4c3ebff)

$secondary_container = rgba(444465ff)

$secondary_fixed = rgba(e2dfffff)

$secondary_fixed_dim = rgba(c4c3ebff)

$shadow = rgba(000000ff)

$source_color = rgba(4d807fff)

$surface = rgba(0c1516ff)

$surface_bright = rgba(323b3dff)

$surface_container = rgba(182123ff)

$surface_container_high = rgba(232b2dff)

$surface_container_highest = rgba(2d3638ff)

$surface_container_low = rgba(141d1fff)

$surface_container_lowest = rgba(071011ff)

$surface_dim = rgba(0c1516ff)

$surface_tint = rgba(f7bc63ff)

$surface_variant = rgba(39494dff)

$tertiary = rgba(8ed1deff)

$tertiary_container = rgba(004f58ff)

$tertiary_fixed = rgba(a9eefaff)

$tertiary_fixed_dim = rgba(8ed1deff)





