$image = Pictures/Wallpapers/paper-planes-and-dreams.jpg

$background = rgba(0c1516ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(293234ff)

$inverse_primary = rgba(825500ff)

$inverse_surface = rgba(dbe4e6ff)

$on_background = rgba(dbe4e6ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(452b00ff)

$on_primary_container = rgba(ffddb3ff)

$on_primary_fixed = rgba(291800ff)

$on_primary_fixed_variant = rgba(633f00ff)

$on_secondary = rgba(2c2d4dff)

$on_secondary_container = rgba(e1e0ffff)

$on_secondary_fixed = rgba(171837ff)

$on_secondary_fixed_variant = rgba(434465ff)

$on_surface = rgba(dbe4e6ff)

$on_surface_variant = rgba(b8cacdff)

$on_tertiary = rgba(00363dff)

$on_tertiary_container = rgba(a9eef9ff)

$on_tertiary_fixed = rgba(001f24ff)

$on_tertiary_fixed_variant = rgba(004f57ff)

$outline = rgba(839497ff)

$outline_variant = rgba(39494cff)

$primary = rgba(f9bb64ff)

$primary_container = rgba(633f00ff)

$primary_fixed = rgba(ffddb3ff)

$primary_fixed_dim = rgba(f9bb64ff)

$scrim = rgba(000000ff)

$secondary = rgba(c3c3ebff)

$secondary_container = rgba(434465ff)

$secondary_fixed = rgba(e1e0ffff)

$secondary_fixed_dim = rgba(c3c3ebff)

$shadow = rgba(000000ff)

$source_color = rgba(518280ff)

$surface = rgba(0c1516ff)

$surface_bright = rgba(323b3cff)

$surface_container = rgba(182123ff)

$surface_container_high = rgba(222c2dff)

$surface_container_highest = rgba(2d3638ff)

$surface_container_low = rgba(141d1fff)

$surface_container_lowest = rgba(071011ff)

$surface_dim = rgba(0c1516ff)

$surface_tint = rgba(f9bb64ff)

$surface_variant = rgba(39494cff)

$tertiary = rgba(8dd1ddff)

$tertiary_container = rgba(004f57ff)

$tertiary_fixed = rgba(a9eef9ff)

$tertiary_fixed_dim = rgba(8dd1ddff)





