#: Basic colors

foreground                      #dbe4e6
background                      #0c1516
background_opacity              0.8
selection_foreground            #442b00
selection_background            #f7bc63


#: Cursor colors

cursor                         	#dbe4e6 
cursor_text_color               #293234


#: URL underline color when hovering with mouse

url_color                       #c4c3eb


#: kitty window border colors and terminal bell colors

active_border_color             #8ed1de
inactive_border_color           #839497
bell_border_color               #ffb4ab

#: Tab bar colors

active_tab_foreground           #b8cacd
active_tab_background           #39494d
inactive_tab_foreground         #dbe4e6
inactive_tab_background         #0c1516
tab_bar_background              none
tab_bar_margin_color            none

#: Colors for marks (marked text in the terminal)

mark1_foreground                #442b00
mark1_background                #624000
mark2_foreground                #2d2d4d
mark2_background                #444465
mark3_foreground                #00363d
mark3_background                #004f58

#: The basic 16 colors

#: black
color0                          #0c1516
color8                          #0c1516

#: red
color1                          #ffb4ab
color9                          #93000a

#: green
color2                          #8ed1de
color10                         #004f58

#: yellow
color3                          #ffddb1
color11                         #f7bc63

#: blue
color4                          #c4c3eb
color12                         #444465

#: magenta
color5                          #815600
color13                         #dbe4e6

#: cyan
color6                          #e2dfff
color14                         #c4c3eb

#: white
color7                          #dbe4e6
color15                         #b8cacd

