#: Basic colors

foreground                      #f1dfdb
background                      #1a110f
background_opacity              0.8
selection_foreground            #561f11
selection_background            #ffb4a2


#: Cursor colors

cursor                         	#f1dfdb 
cursor_text_color               #392e2c


#: URL underline color when hovering with mouse

url_color                       #e7bdb3


#: kitty window border colors and terminal bell colors

active_border_color             #dac58c
inactive_border_color           #a08c88
bell_border_color               #ffb4ab

#: Tab bar colors

active_tab_foreground           #d8c2bd
active_tab_background           #534340
inactive_tab_foreground         #f1dfdb
inactive_tab_background         #1a110f
tab_bar_background              none
tab_bar_margin_color            none

#: Colors for marks (marked text in the terminal)

mark1_foreground                #561f11
mark1_background                #723425
mark2_foreground                #442a23
mark2_background                #5d3f38
mark3_foreground                #3c2f04
mark3_background                #544519

#: The basic 16 colors

#: black
color0                          #1a110f
color8                          #1a110f

#: red
color1                          #ffb4ab
color9                          #93000a

#: green
color2                          #dac58c
color10                         #544519

#: yellow
color3                          #ffdad2
color11                         #ffb4a2

#: blue
color4                          #e7bdb3
color12                         #5d3f38

#: magenta
color5                          #904b3a
color13                         #f1dfdb

#: cyan
color6                          #ffdad2
color14                         #e7bdb3

#: white
color7                          #f1dfdb
color15                         #d8c2bd

