#: Basic colors

foreground                      #dbe4e6
background                      #0c1516
background_opacity              0.8
selection_foreground            #452b00
selection_background            #f9bb64


#: Cursor colors

cursor                         	#dbe4e6 
cursor_text_color               #293234


#: URL underline color when hovering with mouse

url_color                       #c3c3eb


#: kitty window border colors and terminal bell colors

active_border_color             #8dd1dd
inactive_border_color           #839497
bell_border_color               #ffb4ab

#: Tab bar colors

active_tab_foreground           #b8cacd
active_tab_background           #39494c
inactive_tab_foreground         #dbe4e6
inactive_tab_background         #0c1516
tab_bar_background              none
tab_bar_margin_color            none

#: Colors for marks (marked text in the terminal)

mark1_foreground                #452b00
mark1_background                #633f00
mark2_foreground                #2c2d4d
mark2_background                #434465
mark3_foreground                #00363d
mark3_background                #004f57

#: The basic 16 colors

#: black
color0                          #0c1516
color8                          #0c1516

#: red
color1                          #ffb4ab
color9                          #93000a

#: green
color2                          #8dd1dd
color10                         #004f57

#: yellow
color3                          #ffddb3
color11                         #f9bb64

#: blue
color4                          #c3c3eb
color12                         #434465

#: magenta
color5                          #825500
color13                         #dbe4e6

#: cyan
color6                          #e1e0ff
color14                         #c3c3eb

#: white
color7                          #dbe4e6
color15                         #b8cacd

