#: Basic colors

foreground                      #dde4e3
background                      #0e1514
background_opacity              0.8
selection_foreground            #003736
selection_background            #80d5d3


#: Cursor colors

cursor                         	#dde4e3 
cursor_text_color               #2b3231


#: URL underline color when hovering with mouse

url_color                       #b0cccb


#: kitty window border colors and terminal bell colors

active_border_color             #b2c8e8
inactive_border_color           #889392
bell_border_color               #ffb4ab

#: Tab bar colors

active_tab_foreground           #bec9c8
active_tab_background           #3f4948
inactive_tab_foreground         #dde4e3
inactive_tab_background         #0e1514
tab_bar_background              none
tab_bar_margin_color            none

#: Colors for marks (marked text in the terminal)

mark1_foreground                #003736
mark1_background                #00504f
mark2_foreground                #1b3534
mark2_background                #324b4b
mark3_foreground                #1c324b
mark3_background                #334863

#: The basic 16 colors

#: black
color0                          #0e1514
color8                          #0e1514

#: red
color1                          #ffb4ab
color9                          #93000a

#: green
color2                          #b2c8e8
color10                         #334863

#: yellow
color3                          #9cf1ef
color11                         #80d5d3

#: blue
color4                          #b0cccb
color12                         #324b4b

#: magenta
color5                          #006a69
color13                         #dde4e3

#: cyan
color6                          #cce8e7
color14                         #b0cccb

#: white
color7                          #dde4e3
color15                         #bec9c8

